services:
  - type: web
    name: flow-savvy-freelancer-backend
    env: node
    buildCommand: npm install && tsc && prisma generate
    startCommand: node ./dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false